### ISSUE TITLE
Error update on Atom v1.9.9

### ISSUE THREAD

**Issue by tcelestino** [DFreds/code-peek-atom#11]
**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6 (15G31)
**Thrown From**: code-peek package, v1.4.9

**Stack Trace**

![screen shot 2016-08-21 at 5 48 28 pm](https://cloud.githubusercontent.com/assets/190265/17839724/7f2f7fce-67c7-11e6-86e6-44e5f0b9d422.png)

There is a update for package, but when I make to update the error above is show Atom console.

**Comment by DFreds** [comment]
Hmm updating didn't fail for me when I tested on a separate machine. Try uninstalling and reinstalling? Could also be related to a new version of Atom. I'll investigate

**Comment by DFreds** [comment]
Did you try checking that the package.json shown in the stack trace actually exists in that directory? Can't imagine why it wouldn't, but maybe something weird happened.

**Comment by FlorianWendelborn** [comment]
I'm currently trying to reproduce this on macOS 10.11.6, atom 1.9.9, package 1.4.8 -> 1.4.9, let's see if it breaks.

**Comment by FlorianWendelborn** [comment]
Nope, everything seems to work fine, even after a reload.

I'd guess it was some sort of network error (maybe atom.io was down for some seconds).

**Comment by DFreds** [comment]
Awesome, glad it's resolved. :)
