### ISSUE TITLE
Add support for golang .go files

### ISSUE THREAD

**Issue by krohnjw** [DFreds/code-peek-atom#14]
I've been using this locally and it seems to work as expected.   Assuming gofmt is used.

```
   'go':
      regExp: ///
        # Matches func REPLACE( or func (t target) REPLACE(
        func\s+(|\(.*\)\s+)REPLACE\(
      ///
      isTabBased: true
```

Matching:
- func myMethod()
- func (t Target) myMethod()
- func myMethod(a args)
- func (t Target) myMethod(a args)

**Comment by DFreds** [comment]
Awesome, thanks so much! I'll look into adding it later today.

**Comment by DFreds** [comment]
Done! Completed with pull request #15. Thanks so much!
