### ISSUE TITLE
Language type recognition suggestion.

### ISSUE THREAD

**Issue by tongjieme** [DFreds/code-peek-atom#16]
Hello

It seems like the code-peek package recognize the language type base on the file extension. (correct me if i am wrong)

I think it would be more accurate to recognize from the current file syntax which was set in the right bottom of Atom.

![qq 20170204184332](https://cloud.githubusercontent.com/assets/1511418/22617867/f25f8212-eb09-11e6-952a-46c1eda0b46b.png)

**Comment by DFreds** [comment]
Great idea! You're right that it looks at the file extension. I'll look into changing so that it's based on the current syntax.

**Comment by DFreds** [comment]
Solved this. Thanks again for the suggestion. Look for version 1.4.15 shortly
