### ISSUE TITLE
Not compatible with Semanticolor

### ISSUE THREAD

**Issue by marnen** [DFreds/code-peek-atom#21]
I'm trying to use code-peek 1.4.16 with [Semanticolor](https://atom.io/packages/semanticolor), but there's a conflict. The problem is that to do its highlighting, Semanticolor prefixes the name of the current grammar with "semanticolor", so code-peek gives the error "Peek function does not currently support semanticolor - Ruby files".

So...perhaps it should ignore the "semanticolor" prefix or find some other way of determining the language?

**Comment by DFreds** [comment]
1.4.17 will fix this
