### ISSUE TITLE
Need ES6 class shorthand method support

### ISSUE THREAD

**Issue by jonyeezs** [DFreds/code-peek-atom#23]
Many people are moving to ES6.

Kinda cool thing to do nowadays (i myself hate but that's my opinion)

This format isn't supported yet.

```js
 methodName() {
 }
```

**Comment by jonyeezs** [comment]
I could try solve this but i don't understand what `REPLACE` means in the supported-files.coffee?

**Comment by jonyeezs** [comment]
it needs this regex as well:
`\s*REPLACE\(?\s*\(([\,\s\w]*)?\)\s*{`

**Comment by DFreds** [comment]
Hi @jonyeezs,

The REPLACE string is what the selected function replaces before executing the regexp to find the function. Feel free to try and solve it if you want. Otherwise, I might look at it later today or tomorrow.

**Comment by DFreds** [comment]
Also, what is the grammar type for your file? It should say in the lower left hand corner.

**Comment by jonyeezs** [comment]
Mines lower right. Heh.

It's JavaScript. Yeah I realize the replace later on.

I've included my regex in the previous comment.

**Comment by DFreds** [comment]
Added to 1.4.18. Thanks! Let me know if you notice any issues
