### ISSUE TITLE
can i peek functions at current project?

### ISSUE THREAD

**Issue by xingStyle** [DFreds/code-peek-atom#26]
when I open multiple projects,can i peek functions at current project?

**Comment by DFreds** [comment]
Do you mean when you add another project folder?

**Comment by xingStyle** [comment]
yes!is there a way to solve it?

**Comment by DFreds** [comment]
You need to be more specific. Tell me what is happening with an example

**Comment by DFreds** [comment]
I'm unsure what you mean, so I'm going to close this.
