### ISSUE TITLE
support Typescript class

### ISSUE THREAD

**Issue by jonyeezs** [DFreds/code-peek-atom#27]
TS uses classes as JS uses function as constructor.

Here is the propose regex: 
`
class\s+REPLACE(\s+extends\s+[_$a-zA-Z\xA0-\uFFFF][_$a-zA-Z0-9\xA0-\uFFFF]*|)\s+{
`

This should cater for scenarios:
1. `class Replace {}`
2. `class Replace extends Base {`
3. `export class Replace {}`
4. `export class Replace extends Base  {}`

**Comment by DFreds** [comment]
Haven't had a chance to test this out yet, but thanks for this! I'll try it out soon.

**Comment by ghost** [comment]
Tips: (and working with TypeScriptReact :D )
functions:
(private|protected|public)? (static)? \s+ REPLACE \s* \(
interfaces:
interface\s+REPLACE\s*{

**Comment by jonyeezs** [comment]
@avernus88 is that specific to TypeScriptReact?

**Comment by ghost** [comment]
It works with both:
'TypeScript':
      regExp: ///
        # class
        class\s+REPLACE(\s+extends\s+[_$a-zA-Z\xA0-\uFFFF][_$a-zA-Z0-9\xA0-\uFFFF]*|)\s+{
          # or
          |
        # matches 'function REPLACE('
        function \s+ REPLACE \s* \(
          # or
          |
        # matches 'REPLACE = function (' or 'REPLACE: function ('
        REPLACE \s* (=|:) \s* function \s* \(
         |
        # function:
        (private|protected|public)? (static)? \s+ REPLACE \s* \(
        # interface:
         |
        interface\s+REPLACE\s*{
      ///
      isTabBased: false

    'TypeScriptReact':
      regExp: ///
        # class
        class\s+REPLACE(\s+extends\s+[_$a-zA-Z\xA0-\uFFFF][_$a-zA-Z0-9\xA0-\uFFFF]*|)\s+{
          # or
          |
        # matches 'function REPLACE('
        function \s+ REPLACE \s* \(
          # or
          |
        # matches 'REPLACE = function (' or 'REPLACE: function ('
        REPLACE \s* (=|:) \s* function \s* \(
         |
        # function:
        (private|protected|public)? (static)? \s+ REPLACE \s* \(
        # interface:
         |
        interface\s+REPLACE\s*{
      ///
      isTabBased: false

**Comment by DFreds** [comment]
Hey @avernus88, just so I'm 100% clear on the change, do you mind making a pull request? Feel free to add some test files and everything, and I'll merge it in and release it if it looks good. Thanks for your help!

**Comment by DFreds** [comment]
This is amazing guys. Works flawlessly. Thanks so much. Going to release it shortly.
