### ISSUE TITLE
Support TypeScript React

### ISSUE THREAD

**Issue by vinz243** [DFreds/code-peek-atom#28]
Right now `tsx` aren't supported when they could be. Even better would be to support components peek

**Comment by DFreds** [comment]
I believe this grammar type comes from the [Atom Typescript](https://atom.io/packages/atom-typescript) plugin, right? 

I believe the grammar name is TypeScriptReact. I'll work on it.

**Comment by DFreds** [comment]
Fixed. Will either be in the next patch release or the next minor release in a few days.

**Comment by DFreds** [comment]
Decided to do this in a patch. It's in 1.4.19.

**Comment by vinz243** [comment]
Thanks as lot :)
