### ISSUE TITLE
Close panel when clicking 'See entire file'

### ISSUE THREAD

**Issue by ProLoser** [DFreds/code-peek-atom#8]
If I'm opening the full file, I don't need the panel to remain open. It should automatically close itself upon opening the file.

**Comment by ProLoser** [comment]
At the very least, it should do so if there's only 1 matching file, or if you exit the 'preview' of the file (like double clicking on the file if tab preview behavior is enabled)

**Comment by DFreds** [comment]
Great idea. I'll add that behavior in. Thanks!

**Comment by DFreds** [comment]
Fixed as of 1.4.9. It closes if there is only 1 matching file. Otherwise, it'll stay open.
